"""
Django settings for portal_suporte project.

Generated by "django-admin startproject" using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.contrib.messages import constants as messages

# Carrega o .env
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# CONFIGURAÇÕES BÁSICAS

# Lê do .env. Se não achar, usa uma chave insegura 
SECRET_KEY = os.getenv('SECRET_KEY')

# Converte a string 'True'/'False' do .env para booleano do Python
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# APLICAÇÕES E MIDDLEWARE

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tickets", # App
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portal_suporte.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "portal_suporte.wsgi.application"



# BANCO DE DADOS

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('DB_NAME'),
        "USER": os.getenv('DB_USER'),
        "PASSWORD": os.getenv('DB_PASSWORD'),
        "HOST": os.getenv('DB_HOST', 'localhost'),
        "PORT": "5432",
    }
}

# VALIDAÇÃO DE SENHA E I18N

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "pt-br" 
TIME_ZONE = "America/Sao_Paulo" 
USE_I18N = True
USE_TZ = True



# ARQUIVOS ESTÁTICOS E MÍDIA

STATIC_URL = "static/"

# Onde estão seus arquivos originais (CSS do Admin e do Site)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'), 
]

# Onde o Django vai "juntar" tudo no deploy (Railway usa essa pasta)
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

# Engine de compressão do Whitenoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Uploads (Anexos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# AUTENTICAÇÃO E LOGIN

AUTH_USER_MODEL = "tickets.Cliente"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "pagina_inicial"
LOGOUT_REDIRECT_URL = "login"

AUTHENTICATION_BACKENDS = [
    "tickets.backend.EmailBackend", 
    "django.contrib.auth.backends.ModelBackend",
]



# E-MAIL (SMTP)

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.iiotconsol.com" 
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# Pega do .env
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')   
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_DESTINATION = os.getenv('SUPORTE_DESTINATION_EMAIL')
SUPPORT_EMAIL_ADDRESS = os.getenv('SUPORTE_DESTINATION_EMAIL')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# CONFIGURAÇÕES DE SEGURANÇA E AMBIENTE

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000 
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF para Deploy (Permite POST vindo do seu domínio https)
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')

# Mapeamento de Tags do Django para Classes CSS do Bootstrap
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger', # Transforma 'error' em 'alert-danger' (Vermelho)
}

# IBM MAXIMO CONFIG (Adicione isso no final do arquivo) 
MAXIMO_API_URL = os.getenv('MAXIMO_API_URL')
MAXIMO_API_KEY = os.getenv('MAXIMO_API_KEY')