# Generated by Django 5.2.6 on 2025-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="person_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
