# Generated by Django 5.2.6 on 2025-12-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_cliente_person_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sumario",
                    models.CharField(max_length=100, verbose_name="Resumo do Problema"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição Detalhada")),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="anexos_tickets/"
                    ),
                ),
                (
                    "maximo_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID do Chamado (SR)",
                    ),
                ),
                (
                    "status_maximo",
                    models.CharField(
                        choices=[
                            ("NEW", "Novo"),
                            ("QUEUED", "Enfileirado"),
                            ("INPROG", "Em Andamento"),
                            ("PENDING", "Pendente"),
                            ("APPR", "Aprovado"),
                            ("APPFML", "Aprovado pelo Gerenciador de Cumprimento"),
                            ("APPLM", "Aprovado pelo Gerente de Linha"),
                            ("RESOLVED", "Resolvido"),
                            ("CLOSED", "Fechado"),
                            ("CANCELLED", "Cancelada"),
                            ("REJECTED", "Rejeitado"),
                            ("DRAFT", "Rascunho"),
                            ("HISTEDIT", "Editado no Histórico"),
                            ("TSTCLI", "Teste do cliente"),
                            ("TSTCLIOK", "Teste do cliente OK"),
                            ("TSTCLIFAIL", "Teste do cliente falhou"),
                            ("IMPPRODOK", "Implementação em produção OK"),
                            ("AGREUN", "Reunião Agendada"),
                            ("CRITFAIL", "Falha Crítica"),
                            ("ROLLBACK", "Rollback"),
                            ("TREINAMTO", "Treinamento"),
                            ("DOC", "Documentar"),
                            ("SLAHOLD", "Espera de SLA"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Status Atual",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Aberto em"),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última atualização"
                    ),
                ),
                (
                    "ambiente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ambiente",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.area",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "tickets",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
