# Generated by Django 5.2.6 on 2025-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("1", "1 - Crítica"),
                    ("2", "2 - Alta"),
                    ("3", "3 - Média"),
                    ("4", "4 - Baixa"),
                    ("5", "5 - Sem Prioridade"),
                ],
                default="5",
                max_length=2,
                verbose_name="Prioridade",
            ),
        ),
    ]
