# Generated by Django 5.2.6 on 2025-12-30 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_alter_ticket_prioridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ambiente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tickets.ambiente",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tickets.area",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status_maximo",
            field=models.CharField(
                choices=[
                    ("NEW", "Novo"),
                    ("QUEUED", "Em fila"),
                    ("INPROG", "Em Andamento"),
                    ("PENDING", "Pendente"),
                    ("APPR", "Aprovado"),
                    ("APPFML", "Aprovado pelo Gerenciador de Cumprimento"),
                    ("APPLM", "Aprovado pelo Gerente de Linha"),
                    ("RESOLVED", "Resolvido"),
                    ("CLOSED", "Fechado"),
                    ("CANCELLED", "Cancelada"),
                    ("REJECTED", "Rejeitado"),
                    ("DRAFT", "Rascunho"),
                    ("HISTEDIT", "Editado no Histórico"),
                    ("TSTCLI", "Teste do cliente"),
                    ("TSTCLIOK", "Teste do cliente OK"),
                    ("TSTCLIFAIL", "Teste do cliente falhou"),
                    ("IMPPRODOK", "Implementação em produção OK"),
                    ("AGREUN", "Reunião Agendada"),
                    ("CRITFAIL", "Falha Crítica"),
                    ("ROLLBACK", "Rollback"),
                    ("TREINAMTO", "Treinamento"),
                    ("DOC", "Documentar"),
                    ("SLAHOLD", "Espera de SLA"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Status Atual",
            ),
        ),
    ]
