# Generated by Django 5.2.6 on 2025-12-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_alter_ticket_ambiente_alter_ticket_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tickets.area",
            ),
        ),
    ]
