# Generated by Django 5.2.6 on 2026-01-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_alter_ticket_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketInteracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="interacoes_anexos/",
                        verbose_name="Anexo (Opcional)",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoes",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interação",
                "verbose_name_plural": "Interações",
                "db_table": "ticket_interacoes",
                "ordering": ["data_criacao"],
            },
        ),
    ]
