# Generated by Django 5.2.6 on 2026-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_alter_ticketinteracao_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="anexo",
            field=models.FileField(
                blank=True, null=True, upload_to="ticket_anexos/", verbose_name="Anexo"
            ),
        ),
    ]
