# Generated by Django 5.2.6 on 2026-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_notificacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacao",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.AddField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("mensagem", "Nova Mensagem"),
                    ("status", "Mudança de Status"),
                    ("sistema", "Aviso do Sistema"),
                ],
                default="sistema",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notificacao",
            name="titulo",
            field=models.CharField(default="Nova Notificação", max_length=50),
        ),
    ]
