# Generated by Django 5.2.6 on 2026-01-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0014_alter_ticket_status_maximo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="arquivo",
        ),
    ]
