# Generated by Django 5.2.6 on 2026-01-16 20:18

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_remove_ticket_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=tickets.models.ticket_upload_path,
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="maximo_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="ID do Chamado (SR)",
            ),
        ),
        migrations.AlterField(
            model_name="ticketinteracao",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=tickets.models.interacao_upload_path,
                verbose_name="Anexo (Opcional)",
            ),
        ),
    ]
