# Generated by Django 5.2.6 on 2026-01-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0016_alter_ticket_anexo_alter_ticket_maximo_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Endereço de e-mail"
            ),
        ),
    ]
