# Generated by Django 5.2.6 on 2026-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0017_alter_cliente_email"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["cliente", "data_criacao"], name="tickets_cliente_f1989d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status_maximo"], name="tickets_status__1b0b76_idx"
            ),
        ),
    ]
